server:
  #port: 9001
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 4
      worker: 32


spring:
  application:
    name: demo-oss

  profiles:
    include: oss
#    active: sit

ws:
  host: 0.0.0.0
  port: 80